# Generated by Django 5.1.4 on 2025-01-13 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('pending_review', 'Pending Review'), ('review_scheduled', 'Review Scheduled'), ('feedback_provided', 'Feedback Provided'), ('under_approval', 'Under Approval'), ('review_approved', 'Review Approved'), ('review_rejected', 'Review Rejected')], default='pending_review', max_length=20)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_performance_reviews', related_query_name='employee_performance_review', to='employee.employee')),
            ],
        ),
    ]
