# Generated by Django 5.1.4 on 2025-01-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('performance_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='performance_reviews',
            field=models.ManyToManyField(blank=True, related_name='employee_performance_reviews', related_query_name='employee_performance_review', to='performance_review.performancereview'),
        ),
    ]
