# Generated by Django 5.1.4 on 2025-01-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_employees',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_employees',
            field=models.ManyToManyField(to='employee.employee'),
        ),
    ]
