# Generated by Django 5.1.4 on 2025-01-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num_departments', models.IntegerField(default=0)),
                ('num_employees', models.IntegerField(default=0)),
                ('num_projects', models.IntegerField(default=0)),
            ],
        ),
    ]
