# Generated by Django 5.1.4 on 2025-01-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('admin', 'Admin'), ('employee', 'Employee')]),
        ),
    ]
